name: CPO
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _tflow_select=2.3.0=mkl
  - absl-py=0.12.0=py36h06a4308_0
  - astor=0.8.1=py36h06a4308_0
  - blas=1.0=mkl
  - c-ares=1.17.1=h27cfd23_0
  - ca-certificates=2020.12.5=ha878542_0
  - certifi=2020.12.5=py36h5fab9bb_1
  - coverage=5.5=py36h27cfd23_2
  - cython=0.29.22=py36h2531618_0
  - gast=0.4.0=py_0
  - grpcio=1.36.1=py36h2157cd5_1
  - h5py=2.10.0=py36hd6299e0_1
  - hdf5=1.10.6=hb1b8bf9_0
  - importlib-metadata=3.10.0=py36h06a4308_0
  - intel-openmp=2020.2=254
  - keras-applications=1.0.8=py_1
  - keras-preprocessing=1.1.2=pyhd3eb1b0_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libprotobuf=3.14.0=h8c45485_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - markdown=3.3.4=py36h06a4308_0
  - mkl=2020.2=256
  - mkl-service=2.3.0=py36he8ac12f_0
  - mkl_fft=1.3.0=py36h54f3939_0
  - mkl_random=1.1.1=py36h0573a6f_0
  - mock=4.0.3=pyhd3eb1b0_0
  - ncurses=6.2=he6710b0_1
  - numpy=1.19.2=py36h54aff64_0
  - numpy-base=1.19.2=py36hfa32c7d_0
  - openssl=1.1.1k=h27cfd23_0
  - pip=21.0.1=py36h06a4308_0
  - protobuf=3.14.0=py36h2531618_1
  - python=3.6.13=hdb3f193_0
  - python_abi=3.6=1_cp36m
  - readline=8.1=h27cfd23_0
  - scipy=1.5.2=py36h0b6359f_0
  - setuptools=52.0.0=py36h06a4308_0
  - six=1.15.0=py36h06a4308_0
  - sqlite=3.35.4=hdfb4753_0
  - tensorboard=1.13.1=py36hf484d3e_0
  - tensorflow=1.13.1=mkl_py36h27d456a_0
  - tensorflow-base=1.13.1=mkl_py36h7ce6ba3_0
  - tensorflow-estimator=1.13.0=py_0
  - termcolor=1.1.0=py36h06a4308_1
  - tk=8.6.10=hbc83047_0
  - typing_extensions=3.7.4.3=pyha847dfd_0
  - werkzeug=1.0.1=pyhd3eb1b0_0
  - wheel=0.36.2=pyhd3eb1b0_0
  - xz=5.2.5=h7b6447c_0
  - zipp=3.4.1=pyhd3eb1b0_0
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - cloudpickle==1.6.0
    - cycler==0.10.0
    - future==0.18.2
    - gym==0.18.0
    - joblib==1.0.1
    - kiwisolver==1.3.1
    - matplotlib==3.3.4
    - pillow==7.2.0
    - pyglet==1.5.0
    - pyparsing==2.4.7
    - python-dateutil==2.8.1
    - scikit-learn==0.24.1
    - sklearn==0.0
    - threadpoolctl==2.1.0
    - tqdm==4.60.0
prefix: /home/high-cpu/miniconda3/envs/CPO
